accounts/urls.py
from django.urls import path
from . import views



urlpatterns = [
  path("user-detail/<int:pk>/", views.UserDetailView.as_view(), name="user_detail"),
  path("user-update/<int:pk>/", views.UserUpdateView.as_view(), name="user_update"),
  path("subscribe-register/", views.SubscribeRegisterView.as_view(),name="subscribe_register"),
  path("subscribe-cancel/", views.SubscribeCancelView.as_view(),name="subscribe_cancel"),
  path("subscribe-payment/", views.SubscribePaymentView.as_view(),name="subscribe_payment"),

]

nagoyameshi/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("restaurant.urls")),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
]

# 開発サーバーでメディアを配信できるようにする設定
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurant/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path("", views.TopPageView.as_view(), name="top_page"),
  path("company/", views.CompanyView.as_view(), name="company_page"),
  path("terms/", views.TermsView.as_view(), name="terms_page"),
  path("restaurant-detail/<int:pk>/", views.RestaurantDetailView.as_view(), name="restaurant_detail"),
  path("restaurant-list/", views.RestaurantListView.as_view(), name="restaurant_list"),
]

restaurant/models.py
import datetime

from accounts.models import CustomUser
from django.db import models

# Create your models here.

class Category(models.Model):
    """カテゴリーモデル"""
    name = models.CharField(verbose_name='カテゴリー名', max_length=64)
    photo = models.ImageField(verbose_name='写真', blank=True, null=True)
    
    class Meta:
        verbose_name_plural = 'Category'

    def __str__(self):
        return self.name

class Restaurant(models.Model):
    """レストランモデル"""
    name = models.CharField(verbose_name='店舗名', max_length=64)
    description = models.CharField(verbose_name='説明', max_length=128)
    price = models.CharField(verbose_name='価格帯', max_length=32)
    zip_code = models.CharField(verbose_name='郵便番号', max_length=32)
    address = models.CharField(verbose_name='住所', max_length=128)
    business_time = models.CharField(verbose_name='営業時間', max_length=64)
    close_day_of_week = models.CharField(verbose_name='定休日', max_length=32)
    seats_number = models.CharField(verbose_name='座席数', max_length=32)
    category = models.ForeignKey(Category, verbose_name='カテゴリー',
on_delete=models.PROTECT)

    rate = models.FloatField(verbose_name='レート', default=0.0)
    review_num = models.IntegerField(verbose_name='レビュー数', default=0)
    reservation_num = models.IntegerField(verbose_name='予約数', default=0)
    photo = models.ImageField(verbose_name='写真', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)
    
    class Meta:
        verbose_name_plural = 'Restaurant'
    def __str__(self):
        return self.name

class Reservation(models.Model):
    """予約モデル"""
TIMES = (
        ('','選択してください'), (datetime.time(2, 3), '2:30'),
        (datetime.time(3, 0), '3:00'), (datetime.time(3, 30), '3:30'),(datetime.time(4, 0), '4:00'),
        (datetime.time(4, 30), '4:30'),
        (datetime.time(5, 0), '5:00'), (datetime.time(5, 30), '5:30'),(datetime.time(6, 0), '6:00'),
        (datetime.time(6, 30), '6:30'),
        (datetime.time(7, 0), '7:00'), (datetime.time(7, 30), '7:30'),(datetime.time(8, 0), '8:00'),
        (datetime.time(8, 30), '8:30'),
        (datetime.time(9, 0), '9:00'), (datetime.time(9, 30), '9:30'),(datetime.time(10, 0), '10:00'),
        (datetime.time(10, 30), '10:30'),
)

NUMBER_OF_PEOPLE = (
    ('','選択してください'), (1, '1名'), (2, '2名'), (3, '3名'), (4, '4名'),(5, '5名'), (6, '6名'), (7, '7名'),(8, '8名'), (9, '9名'), (10, '10名'),
    (11, '11名'), (12, '12名'), (13, '13名'), (14, '14名'), (15, '15名'),(16, '16名'), (17, '17名'), (18, '18名'),(19, '19名'), (20, '20名'),
    (21, '21名'), (22, '22名'), (23, '23名'), (24, '24名'), (25, '25名'),(26, '26名'), (27, '27名'), (28, '28名'),(29, '29名'), (30, '30名'),(31, '31名'), (32, '32名'), (33, '33名'), (34, '34名'), (35, '35名'),(36, '36名'), (37, '37名'), (38, '38名'),(39, '39名'), (40, '40名'),
    (41, '41名'), (42, '42名'), (43, '43名'), (44, '44名'), (45, '45名'),(46, '46名'), (47, '47名'), (48, '48名'),(49, '49名'), (50, '50名'),
     )

user = models.ForeignKey(CustomUser, verbose_name='ユーザー',on_delete=models.PROTECT, null=True, blank=True)
restaurant = models.ForeignKey(Restaurant, verbose_name='レストラン',on_delete=models.PROTECT)
date = models.DateField(verbose_name='予約日')
time = models.TimeField(verbose_name='時間', choices=TIMES, default='')
number_of_people = models.IntegerField(verbose_name='人数',choices=NUMBER_OF_PEOPLE, default='')
created_at = models.DateTimeField(verbose_name='予約申し込み日時',auto_now_add=True)
updated_at = models.DateTimeField(verbose_name='予約更新日時', auto_now=True)

class Meta:
        verbose_name_plural = 'Reservation'
def __str__(self):
    return self.restaurant.name


class Review(models.Model):
    """レビューモデル"""
    RATES = ((1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'))
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー',on_delete=models.PROTECT, null=True, blank=True)
    restaurant = models.ForeignKey(Restaurant, verbose_name='レストラン',on_delete=models.PROTECT)
    rate = models.IntegerField(verbose_name='レート', default=5, choices=RATES)
    comment = models.TextField(verbose_name='コメント', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='レビュー作成日時',auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='レビュー更新日時',auto_now=True)
    
    class Meta:
        verbose_name_plural = 'Review'
    def __str__(self):
        return self.restaurant.name

class Favorite(models.Model):
    """お気に入りモデル"""
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー',on_delete=models.PROTECT, null=True, blank=True)
    restaurant = models.ForeignKey(Restaurant, verbose_name='レストラン',on_delete=models.PROTECT)
    created_at = models.DateTimeField(verbose_name='お気に入り登録日時',auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='お気に入り更新日時',auto_now=True)
    
    class Meta:
        verbose_name_plural = 'Favorite'
    def __str__(self):
        return self.restaurant.name

restaurant/views.py
from django.db.models import Avg
from django.db.models import Q
from django.shortcuts import render
from django.views import generic


# Create your views here.
from . import models


""" トップ画面=================================="""

class TopPageView(generic.ListView):
    template_name = "top_page.html"
    model = models.Restaurant
    queryset = models.Restaurant.objects.order_by('-rate')
    context_object_name = 'restaurant_list'

""" 会社概要=================================="""
class CompanyView(generic.TemplateView):
    template_name = "layout/company.html"

""" 利用規約=================================="""
class TermsView(generic.TemplateView):
    template_name = "layout/terms.html"


class TopPageView(generic.ListView):
    """ トップ画面=================================="""
    template_name = "top_page.html"
    model = models.Restaurant
    queryset = models.Restaurant.objects.order_by('-rate')
    context_object_name = 'restaurant_list'

    def get_context_data(self, **kwargs):
        if 'price_session' in self.request.session:
            self.request.session['price_session'] = 0
        if 'keyword_session' in self.request.session:
            self.request.session['keyword_session'] =''
        if 'category_session' in self.request.session:
            self.request.session['category_session'] =''
        if 'select_sort' in self.request.session:
            self.request.session['select_sort'] = '-created_at'
        context = super(TopPageView, self).get_context_data(**kwargs)
        category_list = models.Category.objects.all()
        new_restaurant_list = models.Restaurant.objects.all().order_by('-created_at')

        context.update({
            'category_list': category_list,
            'new_restaurant_list': new_restaurant_list,
        })
        return context

class RestaurantDetailView(generic.DetailView):
    """ レストラン詳細画面=================================="""
    template_name = "restaurant/restaurant_detail.html"
    model = models.Restaurant


class RestaurantListView(generic.ListView):
    """ レストラン一覧画面=================================="""
    template_name = "restaurant_list.html"
    model = models.Restaurant

    def get_context_data(self, **kwargs):
        context = super(RestaurantListView, self).get_context_data(**kwargs)
        # get input value
        keyword = self.request.GET.get('keyword')
        category = self.request.GET.get('category')
        price = self.request.GET.get('price')
        select_sort = self.request.GET.get('select_sort')
        button_type = self.request.GET.get('button_type')

        keyword = keyword if keyword is not None else ''
        category = category if category is not None else ''
        price = price if price is not None else '0'
        select_sort = select_sort if select_sort is not None else '-created_at'

    # session control
        self.request.session['select_sort'] = select_sort

        if button_type == 'keyword':
            self.request.session['keyword_session'] = keyword
            self.request.session['category_session'] = ''
            self.request.session['price_session'] = '0'
        
        if button_type == 'category':
            self.request.session['category_session'] = category
            self.request.session['keyword_session'] =''
            self.request.session['price_session'] = '0'
            
        if button_type == 'price':
            self.request.session['price_session'] = price
            self.request.session['keyword_session'] =''
            self.request.session['category_session'] =''

        if button_type == 'select_sort':
            self.request.session['select_sort'] = select_sort

        keyword_session = self.request.session.get('keyword_session')
        category_session = self.request.session.get('category_session')
        price_session = self.request.session.get('price_session')
        select_sort_session = self.request.session.get('select_sort')

        # filtering queryset
        restaurant_list = models.Restaurant.objects.filter(
            Q(name__icontains=keyword_session) | Q(address__icontains=keyword_session) | Q(
                category__name__icontains=keyword_session))
        restaurant_list = restaurant_list.filter(category__name__icontains=category_session)

        if int(price_session) > 0:
            restaurant_data = models.Restaurant.objects.values('id', 'price')
            target_id_list = []

            for data in restaurant_data:
                price_str = data['price']
                price_str = price_str.replace('円','')
                price_str = price_str.replace(',','')
                price_list = price_str.split('～')

                if int(price_list[0]) <= int(price_session) <= int(price_list[1]):
                    target_id_list.append(data['id'])
            restaurant_list = restaurant_list.filter(id__in=target_id_list)

        # 表示順
        restaurant_list = restaurant_list.order_by(select_sort_session)
        category_list = models.Category.objects.all()

        # querysetに含まれるレストランの平均レートを、レストランごとに取得して配列に格納
        average_rate_list = []
        average_rate_star_list = []
        rate_num_list = []

        for restaurant in restaurant_list:
            average_rate = models.Review.objects.filter(restaurant=restaurant).aggregate(Avg('rate'))
            average_rate = average_rate['rate__avg'] if average_rate['rate__avg'] is not None else 0 
            average_rate_list.append(round(average_rate, 2))
        if average_rate % 1 == 0:
            average_rate = int(average_rate)
        else:
            average_rate = round(average_rate * 2) / 2
        average_rate_star_list.append(average_rate)
        
        rate_num = models.Review.objects.filter(restaurant=restaurant).count()
        rate_num_list.append(rate_num)

        context.update({
            'category_list': category_list,
            'keyword_session': keyword_session,
            'category_session': category_session,
            'price_session': price_session,
            'select_sort_session': select_sort_session,
            'restaurant_list': zip(restaurant_list, average_rate_list,
average_rate_star_list, rate_num_list),
    })
        return context

restaurant/templates/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head> 
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>{% block title %}{% endblock %}</title>
      <!-- Fonts -->
      <link rel="dns-prefetch" href="//fonts.gstatic.com">
      <link href="https://fonts.googleapis.com/css2?family=Carter+One&display=swap" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+JP:wght@400;600&display=swap" rel="stylesheet">
      <!-- css -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
      <link href="{% static 'css/nagoyameshi.css' %}" rel="stylesheet">

    {% block stylesheet %}{% endblock %}
  </head>

  <body>
    <div id="app" class="wrapper">
      <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container nagoyameshi-container">
          <a class="navbar-brand app-name" href="{% url 'top_page' %}">
            <div class="d-flex align-items-center">
              <img class="nagoyameshi-logo me-1" src="{% static 'images/logo/logo.png' %}" alt="nagoyameshi">NAGOYAMESHI</div>
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav me-auto"></ul>
            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ms-auto">
              <!-- Authentication Links -->
              {% if user.is_subscribed %}
                <li class="nav-item dropdown">
                  <a id="navbarDropdown" class="nav-linkdropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>{{ user.user_name }}</a>
                  <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" {#TODO:1#} href="{% url 'user_detail' user.id %}">会員情報</a>
                    {# href="{%url 'user_detail' user.id %}">会員情報</a>#}
                    <a class="dropdown-item"{#TODO:2#} href="#">予約一覧</a>
                    {# href="{% url 'reservation_list' %}">予約一覧</a>#}
                    <a class="dropdown-item"{#TODO:3#} href="#">お気に入り一覧</a>
                    {# href="{% url 'favorite_list' %}">お気に入り一覧</a>#}
                    <a class="dropdown-item" {#TODO:4#} href="{% url 'subscribe_payment' %}">お支払い方法</a>
                    {# href="{%url 'subscribe_payment' %}">お支払い方法</a>#}
                    <a class="dropdown-item"{#TODO:5#} href="{% url 'subscribe_cancel' %}">有料プラン解約</a>
                    {# href="{%url 'subscribe_cancel' %}">有料プラン解約</a>#}
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'account_logout' %}">ログアウト</a>
                  </div>
                </li>
              {% else %}
                {% if user.is_authenticated %}
                  <li class="nav-item dropdown">
                    <a id="navbarDropdown" class="nav-linkdropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>{{ user.user_name }}</a>
                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item"{#TODO:6#} href="{% url 'user_detail' user.id %}">会員情報</a>
                    {#href="{% url 'user_detail' user.id %}">会員情報</a>#}
                    <a class="dropdown-item"{#TODO:7#} href="{% url 'subscribe_register' %}">有料プラン登録</a>
                    {#href="{% url 'subscribe_register' %}">有料プラン登録</a>#}
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'account_logout' %}">ログアウト</a>'account_login' %}">ログイン</a>
            </div>
            </li>

              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account_login' %}">ログイン</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account_signup' %}">新規登録</a>
                </li> 
                  {% endif %}
                  {% endif %}
            </ul>
          </div>
        </div>
      </nav>

    {% block content %}{% endblock %}
      <footer class="bg-light">
        <div class="d-flex justify-content-center footer-logo">
            <a class="navbar-brand app-name" href="{% url 'top_page' %}">
              <div class="d-flex align-items-center"><img class="nagoyameshi-logo me-1" src="{% static 'images/logo/logo.png' %}" alt="nagoyameshi">NAGOYAMESHI</div>
            </a>
        </div>
        <div class="d-flex justify-content-center footer-link">
          <a href="{% url 'company_page' %}" class="link-secondary me-3">会社概要</a>
          <a href="{% url 'terms_page' %}" class="link-secondary">利用規約</a>
        </div>

        <p class="text-center text-muted small mb-0">&copy; NAGOYAMESHI All rights reserved.</p>
      </footer>
      </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"  crossorigin="anonymous"></script>
        {% block js_script %}{% endblock %}
  </body>
</html>

restaurant/templates/layout/company.html
{% extends 'layout/base.html' %}
{% block title %} NAGOYAMESHI {% endblock %}
{% block content %}
  <main>
    <div class="container nagoyameshi-container pb-5">
     <div class="row justify-content-center">
      <div class="col-xxl-6 col-xl-7 col-lg-8 col-md-10">
        <nav class="my-3" style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
          <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item"><a href="{% url 'top_page'%}">ホーム</a></li>
            <li class="breadcrumb-item active" aria-current="page">会社概要</li>
          </ol>
        </nav>
        <h1 class="mb-4 text-center">会社概要</h1>
        <div class="container mb-4">
          <div class="row pb-2 mb-2 border-bottom">
            <div class="col-3">
              <span class="fw-bold">会社名></span>
            </div> 
          
              <div class="col">
                <span>NAGOYAMESHI株式会社</span>
              </div>
            </div>
              <div class="row pb-2 mb-2 border-bottom">
                <div class="col-3">
                  <span class="fw-bold">所在地</span>
                </div>
                <div class="col">
                  <span>〒101-0022 東京都千代田区神田練塀町300番地 住友不動産秋葉原駅前ビル5F</span>
                </div>
              </div>
              <div class="row pb-2 mb-2 border-bottom">
                <div class="col-3">
                  <span class="fw-bold">代表者</span>
                </div>
                <div class="col">
                  <span>侍 太郎</span>
                </div>
              </div>
              <div class="row pb-2 mb-2 border-bottom">
                <div class="col-3">
                  <span class="fw-bold">設立</span>
                </div>
                <div class="col">
                  <span>2015年3月19日</span>
                </div>
              </div>
              <div class="row pb-2 mb-2 border-bottom">
                <div class="col-3">
                  <span class="fw-bold">資本金</span>
                </div>
                <div class="col">
                  <span>110,000千円</span>
                </div>
              </div>
              <div class="row pb-2 mb-2 border-bottom">
                <div class="col-3">
                  <span class="fw-bold">事業内容</span>
                </div>
                <div class="col">
                  <span>飲食店等の情報提供サービス</span>
                </div>
              </div>
              <div class="row pb-2 mb-2 border-bottom">
                <div class="col-3">
                  <span class="fw-bold">従業員数</span>
                </div> 
              <div class="col">
                <span>83名</span>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}