accounts/urls.py
from django.urls import path
from . import views



urlpatterns = [
  path("user-detail/<int:pk>/", views.UserDetailView.as_view(), name="user_detail"),
  path("user-update/<int:pk>/", views.UserUpdateView.as_view(), name="user_update"),
  path("subscribe-register/", views.SubscribeRegisterView.as_view(),name="subscribe_register"),
  path("subscribe-cancel/", views.SubscribeCancelView.as_view(),name="subscribe_cancel"),
  path("subscribe-payment/", views.SubscribePaymentView.as_view(),name="subscribe_payment"),

]

nagoyameshi/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("restaurant.urls")),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
]

# 開発サーバーでメディアを配信できるようにする設定
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurant/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path("", views.TopPageView.as_view(), name="top_page"),
  path("company/", views.CompanyView.as_view(), name="company_page"),
  path("terms/", views.TermsView.as_view(), name="terms_page"),
  path("restaurant-detail/<int:pk>/", views.RestaurantDetailView.as_view(), name="restaurant_detail"),
  path("restaurant-list/", views.RestaurantListView.as_view(), name="restaurant_list"),
]

restaurant/models.py
import datetime

from accounts.models import CustomUser
from django.db import models

# Create your models here.

class Category(models.Model):
    """カテゴリーモデル"""
    name = models.CharField(verbose_name='カテゴリー名', max_length=64)
    photo = models.ImageField(verbose_name='写真', blank=True, null=True)
    
    class Meta:
        verbose_name_plural = 'Category'

    def __str__(self):
        return self.name

class Restaurant(models.Model):
    """レストランモデル"""
    name = models.CharField(verbose_name='店舗名', max_length=64)
    description = models.CharField(verbose_name='説明', max_length=128)
    price = models.CharField(verbose_name='価格帯', max_length=32)
    zip_code = models.CharField(verbose_name='郵便番号', max_length=32)
    address = models.CharField(verbose_name='住所', max_length=128)
    business_time = models.CharField(verbose_name='営業時間', max_length=64)
    close_day_of_week = models.CharField(verbose_name='定休日', max_length=32)
    seats_number = models.CharField(verbose_name='座席数', max_length=32)
    category = models.ForeignKey(Category, verbose_name='カテゴリー',
on_delete=models.PROTECT)

    rate = models.FloatField(verbose_name='レート', default=0.0)
    review_num = models.IntegerField(verbose_name='レビュー数', default=0)
    reservation_num = models.IntegerField(verbose_name='予約数', default=0)
    photo = models.ImageField(verbose_name='写真', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)
    
    class Meta:
        verbose_name_plural = 'Restaurant'
    def __str__(self):
        return self.name

class Reservation(models.Model):
    """予約モデル"""
TIMES = (
        ('','選択してください'), (datetime.time(2, 3), '2:30'),
        (datetime.time(3, 0), '3:00'), (datetime.time(3, 30), '3:30'),(datetime.time(4, 0), '4:00'),
        (datetime.time(4, 30), '4:30'),
        (datetime.time(5, 0), '5:00'), (datetime.time(5, 30), '5:30'),(datetime.time(6, 0), '6:00'),
        (datetime.time(6, 30), '6:30'),
        (datetime.time(7, 0), '7:00'), (datetime.time(7, 30), '7:30'),(datetime.time(8, 0), '8:00'),
        (datetime.time(8, 30), '8:30'),
        (datetime.time(9, 0), '9:00'), (datetime.time(9, 30), '9:30'),(datetime.time(10, 0), '10:00'),
        (datetime.time(10, 30), '10:30'),
)

NUMBER_OF_PEOPLE = (
    ('','選択してください'), (1, '1名'), (2, '2名'), (3, '3名'), (4, '4名'),(5, '5名'), (6, '6名'), (7, '7名'),(8, '8名'), (9, '9名'), (10, '10名'),
    (11, '11名'), (12, '12名'), (13, '13名'), (14, '14名'), (15, '15名'),(16, '16名'), (17, '17名'), (18, '18名'),(19, '19名'), (20, '20名'),
    (21, '21名'), (22, '22名'), (23, '23名'), (24, '24名'), (25, '25名'),(26, '26名'), (27, '27名'), (28, '28名'),(29, '29名'), (30, '30名'),(31, '31名'), (32, '32名'), (33, '33名'), (34, '34名'), (35, '35名'),(36, '36名'), (37, '37名'), (38, '38名'),(39, '39名'), (40, '40名'),
    (41, '41名'), (42, '42名'), (43, '43名'), (44, '44名'), (45, '45名'),(46, '46名'), (47, '47名'), (48, '48名'),(49, '49名'), (50, '50名'),
     )

user = models.ForeignKey(CustomUser, verbose_name='ユーザー',on_delete=models.PROTECT, null=True, blank=True)
restaurant = models.ForeignKey(Restaurant, verbose_name='レストラン',on_delete=models.PROTECT)
date = models.DateField(verbose_name='予約日')
time = models.TimeField(verbose_name='時間', choices=TIMES, default='')
number_of_people = models.IntegerField(verbose_name='人数',choices=NUMBER_OF_PEOPLE, default='')
created_at = models.DateTimeField(verbose_name='予約申し込み日時',auto_now_add=True)
updated_at = models.DateTimeField(verbose_name='予約更新日時', auto_now=True)

class Meta:
        verbose_name_plural = 'Reservation'
def __str__(self):
    return self.restaurant.name


class Review(models.Model):
    """レビューモデル"""
    RATES = ((1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'))
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー',on_delete=models.PROTECT, null=True, blank=True)
    restaurant = models.ForeignKey(Restaurant, verbose_name='レストラン',on_delete=models.PROTECT)
    rate = models.IntegerField(verbose_name='レート', default=5, choices=RATES)
    comment = models.TextField(verbose_name='コメント', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='レビュー作成日時',auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='レビュー更新日時',auto_now=True)
    
    class Meta:
        verbose_name_plural = 'Review'
    def __str__(self):
        return self.restaurant.name

class Favorite(models.Model):
    """お気に入りモデル"""
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー',on_delete=models.PROTECT, null=True, blank=True)
    restaurant = models.ForeignKey(Restaurant, verbose_name='レストラン',on_delete=models.PROTECT)
    created_at = models.DateTimeField(verbose_name='お気に入り登録日時',auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='お気に入り更新日時',auto_now=True)
    
    class Meta:
        verbose_name_plural = 'Favorite'
    def __str__(self):
        return self.restaurant.name

restaurant/views.py
from django.db.models import Avg
from django.db.models import Q
from django.shortcuts import render
from django.views import generic


# Create your views here.
from . import models


""" トップ画面=================================="""

class TopPageView(generic.ListView):
    template_name = "top_page.html"
    model = models.Restaurant
    queryset = models.Restaurant.objects.order_by('-rate')
    context_object_name = 'restaurant_list'

""" 会社概要=================================="""
class CompanyView(generic.TemplateView):
    template_name = "layout/company.html"

""" 利用規約=================================="""
class TermsView(generic.TemplateView):
    template_name = "layout/terms.html"


class TopPageView(generic.ListView):
    """ トップ画面=================================="""
    template_name = "top_page.html"
    model = models.Restaurant
    queryset = models.Restaurant.objects.order_by('-rate')
    context_object_name = 'restaurant_list'

    def get_context_data(self, **kwargs):
        if 'price_session' in self.request.session:
            self.request.session['price_session'] = 0
        if 'keyword_session' in self.request.session:
            self.request.session['keyword_session'] =''
        if 'category_session' in self.request.session:
            self.request.session['category_session'] =''
        if 'select_sort' in self.request.session:
            self.request.session['select_sort'] = '-created_at'
        context = super(TopPageView, self).get_context_data(**kwargs)
        category_list = models.Category.objects.all()
        new_restaurant_list = models.Restaurant.objects.all().order_by('-created_at')

        context.update({
            'category_list': category_list,
            'new_restaurant_list': new_restaurant_list,
        })
        return context

class RestaurantDetailView(generic.DetailView):
    """ レストラン詳細画面=================================="""
    template_name = "restaurant/restaurant_detail.html"
    model = models.Restaurant


class RestaurantListView(generic.ListView):
    """ レストラン一覧画面=================================="""
    template_name = "restaurant_list.html"
    model = models.Restaurant

    def get_context_data(self, **kwargs):
        context = super(RestaurantListView, self).get_context_data(**kwargs)
        # get input value
        keyword = self.request.GET.get('keyword')
        category = self.request.GET.get('category')
        price = self.request.GET.get('price')
        select_sort = self.request.GET.get('select_sort')
        button_type = self.request.GET.get('button_type')

        keyword = keyword if keyword is not None else ''
        category = category if category is not None else ''
        price = price if price is not None else '0'
        select_sort = select_sort if select_sort is not None else '-created_at'

    # session control
        self.request.session['select_sort'] = select_sort

        if button_type == 'keyword':
            self.request.session['keyword_session'] = keyword
            self.request.session['category_session'] = ''
            self.request.session['price_session'] = '0'
        
        if button_type == 'category':
            self.request.session['category_session'] = category
            self.request.session['keyword_session'] =''
            self.request.session['price_session'] = '0'
            
        if button_type == 'price':
            self.request.session['price_session'] = price
            self.request.session['keyword_session'] =''
            self.request.session['category_session'] =''

        if button_type == 'select_sort':
            self.request.session['select_sort'] = select_sort

        keyword_session = self.request.session.get('keyword_session')
        category_session = self.request.session.get('category_session')
        price_session = self.request.session.get('price_session')
        select_sort_session = self.request.session.get('select_sort')

        # filtering queryset
        restaurant_list = models.Restaurant.objects.filter(
            Q(name__icontains=keyword_session) | Q(address__icontains=keyword_session) | Q(
                category__name__icontains=keyword_session))
        restaurant_list = restaurant_list.filter(category__name__icontains=category_session)

        if int(price_session) > 0:
            restaurant_data = models.Restaurant.objects.values('id', 'price')
            target_id_list = []

            for data in restaurant_data:
                price_str = data['price']
                price_str = price_str.replace('円','')
                price_str = price_str.replace(',','')
                price_list = price_str.split('～')

                if int(price_list[0]) <= int(price_session) <= int(price_list[1]):
                    target_id_list.append(data['id'])
            restaurant_list = restaurant_list.filter(id__in=target_id_list)

        # 表示順
        restaurant_list = restaurant_list.order_by(select_sort_session)
        category_list = models.Category.objects.all()

        # querysetに含まれるレストランの平均レートを、レストランごとに取得して配列に格納
        average_rate_list = []
        average_rate_star_list = []
        rate_num_list = []

        for restaurant in restaurant_list:
            average_rate = models.Review.objects.filter(restaurant=restaurant).aggregate(Avg('rate'))
            average_rate = average_rate['rate__avg'] if average_rate['rate__avg'] is not None else 0 
            average_rate_list.append(round(average_rate, 2))
        if average_rate % 1 == 0:
            average_rate = int(average_rate)
        else:
            average_rate = round(average_rate * 2) / 2
        average_rate_star_list.append(average_rate)
        
        rate_num = models.Review.objects.filter(restaurant=restaurant).count()
        rate_num_list.append(rate_num)

        context.update({
            'category_list': category_list,
            'keyword_session': keyword_session,
            'category_session': category_session,
            'price_session': price_session,
            'select_sort_session': select_sort_session,
            'restaurant_list': zip(restaurant_list, average_rate_list,
average_rate_star_list, rate_num_list),
    })
        return context

restaurant/templates/restaurant/restaurant_detail.html
{% extends "layout/base.html" %}
{% load static %}
{% block title %}NAGOYAMESHI{% endblock %}
{% block content %}
<main>
  <div class="container nagoyameshi-container pb-5">
    <div class="row justify-content-center">
      <div class="col-xxl-6 col-xl-7 col-lg-8 col-md-10">
        <nav class="my-3" style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
          <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item"><a href="{% url 'top_page' %}">ホーム</a></li>
            <li class="breadcrumb-item">
              {# TODO:1#}
                <a href="{% url 'restaurant_list' %}?keyword=&button_type=keyword %}">店舗一覧</a>
                  {# <a href="{% url 'restaurant_list' %}?keyword=&button_type=keyword">店舗一覧</a>#}
            </li>
            <li class="breadcrumb-item active" aria-current="page">店舗詳細</li>
          </ol>
        </nav>
          <h1 class="mb-2 text-center">{{ object.name }}</h1>
            <p class="text-center">
              <span class="star-rating me-1" data-rate="{{ average_rate_star }}"></span>
                {{ average_rate }} （{{ rate_count }}件）
            </p>
              <ul class="nav nav-tabs mb-2">
                <li class="nav-item">
                  <a class="nav-link active bg-primary text-white" aria-current="page" href="{% url 'restaurant_detail' object.id %}">トップ</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link link-dark"
                    {# TODO:2#} href="#">予約</a>
                      {# href="{% url 'reservation_create' object.id %}">予約</a>#}
                </li>
                <li class="nav-item">
                  <a class="nav-link link-dark"
                    {# TODO:3#} href="#">レビュー</a>
                    {# href="{% url 'review_list' object.id %}">レビュー</a>#}
                </li>
              </ul>
              <div class="mb-2">
                {% if object.photo %}
                  <img src="{{ object.photo.url }}" class="w-100">
                    {% endif %}
              </div>
                <div class="container">
                  <div class="row pb-2 mb-2 border-bottom">
                    <div class="col-2">
                      <span class="fw-bold">店舗名</span>
                    </div>
                      <div class="col">
                        <span>{{ object.name }}</span>
                      </div>         
                  </div>
                  <div class="row pb-2 mb-2 border-bottom">
                    <div class="col-2">
                      <span class="fw-bold">説明</span>
                    </div>
                    <div class="col">
                      <span>{{ object.description }}</span>
                    </div>
                    </div>
                      <div class="row pb-2 mb-2 border-bottom">
                        <div class="col-2">
                          <span class="fw-bold">価格帯</span>
                        </div>
                          <div class="col">
                            <span>{{ object.price }}</span>
                          </div>
                        </div>
                          <div class="row pb-2 mb-2 border-bottom">
                            <div class="col-2">
                              <span class="fw-bold">郵便番号</span>
                            </div>
                          <div class="col">
                            <span>{{ object.zip_code }}</span>
                          </div>
                        </div>
                          <div class="row pb-2 mb-2 border-bottom">
                            <div class="col-2">
                              <span class="fw-bold">住所</span>
                            </div>
                            <div class="col">
                              <span>{{ object.address }}</span>
                            </div>
                          </div>
                            <div class="row pb-2 mb-2 border-bottom">
                              <div class="col-2">
                                <span class="fw-bold">営業時間</span>
                              </div>
                                <div class="col">
                                  <span>{{ object.business_time }}</span>
                                </div>
                            </div>
                            <div class="row pb-2 mb-2 border-bottom">
                              <div class="col-2">
                                <span class="fw-bold">定休日</span>
                              </div>
                              <div class="col d-flex">
                                <div>
                                  {{ object.close_day_of_week }}
                                </div>
                              </div>
                            </div>
                            <div class="row pb-2 mb-2 border-bottom">
                              <div class="col-2">
                                <span class="fw-bold">座席数</span>
                              </div>
                                <div class="col">
                                  <span>{{ object.seats_number }}</span>
                                </div>
                            </div>
                            <div class="row pb-2 mb-4 border-bottom">
                              <div class="col-2">
                                <span class="fw-bold">カテゴリ</span>
                              </div>
                                <div class="col d-flex">
                                 <div>
                                   {{ object.category }}
                                  </div>
                              </div>
                            </div>
                            <form method="POST" enctype="multipart/form-data" class="text-center">
                              {% csrf_token %}
                              {% if is_favorite %}
                              <button type="submit" class="btn btn-outline-primary shadow-sm w-50 remove-favorite-button">
                              ♥ お気に入り解除
                              </button>
                              {% else %}
                              <button type="submit" class="btn btn-primary text-white shadow-sm w-50">
                              ♥ お気に入り追加
                              </button>
                              {% endif %}
                            </form>
           </div>
        </div>
     </div>
  </div>
</main>
{% endblock %}

restaurant/templates/restaurant/restaurant_list.html
{% extends "layout/base.html" %}
{% load static %}
{% block title %}NAGOYAMESHI{% endblock %}
{% block content %}
<main>
  <div class="container nagoyameshi-container pb-5">
    <div class="row justify-content-center">
      <nav class="my-3" style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
        <ol class="breadcrumb mb-0">
          <li class="breadcrumb-item"><a href="{% url 'top_page' %}">ホーム</a></li>
          <li class="breadcrumb-item active" aria-current="page">店舗一覧</li>
        </ol>
      </nav>
        <div class="col-xl-3 col-lg-4 col-md-12">
          <form method="GET" class="w-100 mb-3">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="店舗名・エリア・カテゴリ" name="keyword" value={% if keyword_session %}{{keyword_session }}{% else %}""{% endif %}> 
              <input type="hidden" name="button_type" value="keyword">
              <button type="submit" class="btn btn-primary text-white shadow-sm">検索</button>
            </div>
          </form>
            <div class="card mb-3">
              <div class="card-header">カテゴリから探す</div>
                <div class="card-body">
                  <form method="GET" class="w-100">
                    <div class="form-group mb-3">
                      <select class="form-control form-select" name="category" required>
                        <option value="">選択してください</option>
                        {% for category in category_list %}
                        <option value="{{ category.name }}"
                          {% if category_session == category.name %}selected{% endif %}>{{ category.name }}
                        </option>
                        {% endfor %}
                      </select>
                    </div>
                      <input type="hidden" name="button_type" value="category">
                      <div class="form-group">
                        <button type="submit" class="btn btn-primary text-white shadow-sm w-100">検索</button>
                      </div>
                  </form>
                </div>
              </div>
                <div class="card mb-3">
                  <div class="card-header">予算から探す</div>
                    <div class="card-body">
                      <form method="GET" class="w-100">
                        <div class="form-group mb-3">
                          <select class="form-control form-select" name="price" required>
                            <option value="">選択してください</option>
                            <option value="500" {% if price_session == "500" %}selected{% endif %}>500円</option>
                              <option value="1000" {% if
                              price_session == "1000" %}selected{% endif %}>1,000円</option>
                              <option value="1500" {% if
                                price_session == "1500" %}selected{% endif %}>1,500円
                              </option>
                              <option value="2000" {% if
                                price_session == "2000" %}selected{% endif %}>2,000円
                              </option>
                              <option value="2500" {% if
                                price_session == "2500" %}selected{% endif %}>2,500円
                              </option>
                              <option value="3000" {% if
                                price_session == "3000" %}selected{% endif %}>3,000円
                              </option>
                              <option value="3500" {% if
                                price_session == "3500" %}selected{% endif %}>3,500円
                              </option>
                              <option value="4000" {% if
                                price_session == "4000" %}selected{% endif %}>4,000円
                              </option>
                              <option value="4500" {% if
                                price_session == "4500" %}selected{% endif %}>4,500円
                              </option>
                              <option value="5000" {% if
                                price_session == "5000" %}selected{% endif %}>5,000円
                              </option>
                              <option value="5500" {% if
                                price_session == "5500" %}selected{% endif %}>5,500円
                              </option>
                              <option value="6000" {% if
                                price_session == "6000" %}selected{% endif %}>6,000円
                              </option>
                              <option value="6500" {% if
                                price_session == "6500" %}selected{% endif %}>6,500円
                              </option>
                              <option value="7000" {% if
                              price_session == "7000" %}selected{% endif %}>7,000円
                              </option>
                              <option value="7500" {% if
                                price_session == "7500" %}selected{% endif %}>7,500円
                              </option>
                              <option value="8000" {% if
                                price_session == "8000" %}selected{% endif %}> 8,000円
                              </option>
                              <option value="8500" {% if
                                price_session == "8500" %}selected{% endif %}>8,500円
                              </option>
                              <option value="9000" {% if
                                price_session == "9000" %}selected{% endif %}>9,000円
                              </option>
                              <option value="9500" {% if
                                price_session == "9500" %}selected{% endif %}>9,500円
                              </option>
                              <option value="10000" {% if
                              price_session == "10000" %}selected{% endif %}>10,000円
                              </option>
                         </select>
                        </div>
                          <input type="hidden" name="button_type" value="price">
                          <div class="form-group">
                            <button type="submit" class="btn btn-primary text-white shadow-sm w-100">検索</button>
                          </div>
                      </form>
                  </div>
                </div>
             </div>
              <div class="col">
                <div class="d-flex justify-content-between flex-wrap">
                 <p class="fs-5 mb-3">
                  {{ restaurant_list.count }}件の店舗が見つかりました<span class="fs-6"> </span>
                </p>
                  <form method="GET" class="mb-3 sort-box">
                    <select class="form-select form-select-sm" name="select_sort" aria-label=".form-select-sm example" onChange="this.form.submit();">
                      <option value="-created_at" hidden>掲載日が新しい順</option>
                      <option value="-created_at" {% if select_sort_session == "-created_at" %}selected{% endif %}>掲載日が新しい順</option>
                      <option value="price" {% if select_sort_session == "price" %}selected{% endif %}>価格が安い順</option>
                      <option value="-rate" {% if select_sort_session == "-rate" %}selected{% endif %}>評価が高い順</option>
                      <option value="-reservation_num" {% if select_sort_session == "-reservation_num" %}selected{% endif %}>予約数が多い順</option>
                    </select>
                     <input type="hidden" name="button_type" value="select_sort">
                  </form>
              </div>
                {% for restaurant,rate,rate_star,rate_num in restaurant_list %}
                <div class="mb-3">
                  <a href="{% url 'restaurant_detail' restaurant.id%}" class="link-dark card-link">
                    <div class="card h-100">
                      <div class="row g-0">
                       <div class="col-md-4">
                        {% if restaurant.photo %}
                           <img src="{{ restaurant.photo.url }}"
                            class="card-img-top horizontal-card-image">
                        {% endif %}
                </div>
                <div class="col-md-8">
                  <div class="card-body">
                  <h3 class="card-title">{{ restaurant.name }}</h3>
                  <div class="col d-flex text-secondary">
                    <div>
                      {{ restaurant.category }}
                    </div>
                  </div>
                  <hr class="my-2">
                  <p class="mb-1">
                    <span class="star-rating me-1" data-rate="{{ rate_star }}"></span>
                    {{ rate }} （{{ rate_num }} 件）
                  </p>
                  <div class="mb-1">
                   <span>{{ restaurant.price }}</span>
                  </div>
                  <p class="card-text">{{ restaurant.description }}</p>
                </div>
              </div>
            </div>
           </div>
          </a>
        </div>
          {% endfor %}
        <div class="d-flex justify-content-center"></div>
      </div>
    </div>
  </div>
</main>
{% endblock %}
{% endblock %}